### ISSUE TITLE
Huge finale4 particle issue

### ISSUE THREAD

**Issue by Tannermanner2008** [URAKOLOUY5/gp2#25]
Finale4 literally freezes the game a few frames after the map finishes loading due to the particle.lua file trying to add "-2147483648" particles

 "Weird particle count -2147483648 in InitializeNewParticles (active: -2147483648, max: 20)"

This should probably be marked as Critical due to this literally making the game unbeatable

**Comment by URAKOLOUY5** [comment]
It's something with paint_bomb_fx,pcf

```
blob_curve_blue
blob_curve_orange
blob_curve
```

maybe because of unimplemented 'render_blobs'
I'll just mark them as broken then
