### ISSUE TITLE
some models and sounds are the portal 1 versions instead of portal 2

### ISSUE THREAD

**Issue by Goruku123456** [URAKOLOUY5/gp2#38]
to be more specific, the cubes, the buttons, and the portal gun. (portal 2 default gun and potato gun not showing up and only using portal 1 noises (portal 2 default gun and potato gun not showing up.
their may be more issues with models and sounds like this, but those are the ones i came across.

also i keep hearing the "oh fiddlesticks" noise.

**Comment by URAKOLOUY5** [comment]
Unmount Portal 1
