### ISSUE TITLE
unable to shoot moon in last cutscene

### ISSUE THREAD

**Issue by Goruku123456** [URAKOLOUY5/gp2#45]

**Comment by URAKOLOUY5** [comment]
Duplicate of #34

**Comment by Goruku123456** [comment]
My bad about the duplicates, I didn’t see the second page. Sorry

**Comment by URAKOLOUY5** [comment]
That's fine, just precheck if there any related issues to your problem

**Comment by Goruku123456** [comment]
Thanks, I will. Great mod btw.
